export const OPEN_ERROR_MESSAGE = 'OPEN_ERROR_MESSAGE'
export const OPEN_WARNING_MESSAGE = 'OPEN_WARNING_MESSAGE'
export const OPEN_SUCCESS_MESSAGE = 'OPEN_SUCCESS_MESSAGE'
export const CLOSE_MESSAGE = 'CLOSE_MESSAGE'
